dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8
  - openjdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "skjolber-github"
script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
